site_name: "Документация SpaceAI"

theme:
  name: "material"
  language: "ru"
  palette:
    - scheme: "slate"
      primary: "black"
      accent: "white"
      toggle:
        icon: "material/weather-night"
        name: "Включить светлую тему"

    - scheme: "default"
      primary: "black"
      accent: "white"
      toggle:
        icon: "material/weather-sunny"
        name: "Включить тёмную тему"

  features:
    - "header.autohide"
    - "navigation.instant"
    - "navigation.instant.prefetch"
    - "navigation.instant.progress"
    - "navigation.footer"
    - "content.action.edit"
    - "content.action.view"
  
  icon:
    repo: "svg/github"

  logo: "assets/svg/logo.svg"
  favicon: "assets/svg/logo.svg"

extra:
  generator: true
  social:
    - icon: "svg/github"
      link: "https://github.com/spaceaipowered"
    - icon: "svg/discord"
      link: "https://discord.gg/WQESPYEdmw"

markdown_extensions: ["admonition"]

extra_javascript: ["assets/javascript/index.js"]
extra_css: ["assets/style/style.css"]

repo_url: "https://github.com/spaceaipowered/docs"
repo_name: "spaceaipowered/docs"
edit_uri: "edit/main/docs/"

nav:
  - "О проекте": "index.md"
  - "FAQ": "faq.md"
  - "Команды": "commands.md"
